"""Agent model mapping table for AGENTS.md.

Port of src/utils/agents-model-table.ts.
"""

from __future__ import annotations

from dataclasses import dataclass

from omx.agents.roles import AGENT_BY_NAME, AgentDefinition

OMX_MODELS_START_MARKER = "<!-- OMX:MODELS:START -->"
OMX_MODELS_END_MARKER = "<!-- OMX:MODELS:END -->"
_TEAM_MODEL_RESOLUTION_END = "</team_model_resolution>"


@dataclass(frozen=True)
class AgentsModelTableContext:
    """Resolved model names for table generation.

    Attributes:
        frontier_model: Model used for frontier-class roles.
        spark_model: Model used for fast/spark roles.
        subagent_default_model: Default model for standard subagents.
    """

    frontier_model: str
    spark_model: str
    subagent_default_model: str


def _escape_table_cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def _format_role_label(role: str) -> str:
    return role if "(" in role else f"`{role}`"


def _get_agent_recommended_model(
    agent: AgentDefinition,
    context: AgentsModelTableContext,
) -> str:
    if agent.name == "executor":
        return context.frontier_model
    match agent.model_class:
        case "fast":
            return context.spark_model
        case "frontier":
            return context.frontier_model
        case _:
            return context.subagent_default_model


def _get_agent_use_case(agent: AgentDefinition) -> str:
    return f"{agent.description} ({agent.posture}, {agent.model_class})"


def _build_table_row(
    role: str, model: str, reasoning_effort: str, use_case: str
) -> str:
    rl = _escape_table_cell(_format_role_label(role))
    ml = _escape_table_cell(f"`{model}`")
    re_ = _escape_table_cell(reasoning_effort)
    uc = _escape_table_cell(use_case)
    return f"| {rl} | {ml} | {re_} | {uc} |"


def build_agents_model_table(
    context: AgentsModelTableContext,
    definitions: dict[str, AgentDefinition] | None = None,
) -> str:
    """Build the markdown model-capability table body.

    Args:
        context: Resolved model context.
        definitions: Agent definitions dict (defaults to ``AGENT_BY_NAME``).

    Returns:
        Markdown table string.
    """
    defs = definitions if definitions is not None else AGENT_BY_NAME
    rows = [
        _build_table_row(
            "Frontier (leader)",
            context.frontier_model,
            "high",
            "Primary leader/orchestrator for planning, coordination, and frontier-class reasoning.",
        ),
        _build_table_row(
            "Spark (explorer/fast)",
            context.spark_model,
            "low",
            "Fast triage, explore, lightweight synthesis, and low-latency routing.",
        ),
        _build_table_row(
            "Standard (subagent default)",
            context.subagent_default_model,
            "high",
            "Default standard-capability model for installable specialists and secondary worker lanes unless a role is explicitly frontier or spark.",
        ),
        *(
            _build_table_row(
                agent.name,
                _get_agent_recommended_model(agent, context),
                agent.reasoning_effort,
                _get_agent_use_case(agent),
            )
            for agent in defs.values()
        ),
    ]

    lines = [
        "## Model Capability Table",
        "",
        "Auto-generated by `omx setup` from the current `config.toml` plus OMX model overrides.",
        "",
        "| Role | Model | Reasoning Effort | Use Case |",
        "| --- | --- | --- | --- |",
        *rows,
    ]
    return "\n".join(lines)


def render_agents_model_table_block(
    context: AgentsModelTableContext,
    definitions: dict[str, AgentDefinition] | None = None,
) -> str:
    """Render the full model table block with start/end markers.

    Args:
        context: Resolved model context.
        definitions: Agent definitions dict.

    Returns:
        Marker-delimited model table block.
    """
    return "\n".join(
        [
            OMX_MODELS_START_MARKER,
            build_agents_model_table(context, definitions),
            OMX_MODELS_END_MARKER,
        ]
    )


def upsert_agents_model_table(
    content: str,
    context: AgentsModelTableContext,
    definitions: dict[str, AgentDefinition] | None = None,
) -> str:
    """Insert or replace the model table block in AGENTS.md content.

    Args:
        content: Existing AGENTS.md content.
        context: Resolved model context.
        definitions: Agent definitions dict.

    Returns:
        Updated content with the model table block.
    """
    block = render_agents_model_table_block(context, definitions)
    start_idx = content.find(OMX_MODELS_START_MARKER)
    end_idx = content.find(OMX_MODELS_END_MARKER)

    if start_idx >= 0 and end_idx > start_idx:
        replace_end = end_idx + len(OMX_MODELS_END_MARKER)
        return content[:start_idx] + block + content[replace_end:]

    insertion_anchor = f"{_TEAM_MODEL_RESOLUTION_END}\n\n---"
    if insertion_anchor in content:
        return content.replace(
            insertion_anchor,
            f"{_TEAM_MODEL_RESOLUTION_END}\n\n{block}\n\n---",
        )

    trailing = "" if content.endswith("\n") else "\n"
    return f"{content}{trailing}\n{block}\n"
