"""HUD — tmux statusline rendering.

Full module entry point for HUD types, colors, constants,
state, renderer, authority, reconcile, and tmux integration.
"""

from omx.hud.types import (
    AutopilotStateForHud,
    AutoresearchStateForHud,
    DeepInterviewStateForHud,
    DEFAULT_HUD_CONFIG,
    HudConfig,
    HudFlags,
    HudGitConfig,
    HudGitDisplay,
    HudMetrics,
    HudNotifyState,
    HudPreset,
    HudRenderContext,
    RalphStateForHud,
    RalplanStateForHud,
    ResolvedHudConfig,
    ResolvedHudGitConfig,
    SessionStateForHud,
    TeamStateForHud,
    UltraqaStateForHud,
    UltraworkStateForHud,
)
from omx.hud.colors import (
    bold,
    cyan,
    dim,
    get_ralph_color,
    green,
    is_color_enabled,
    set_color_enabled,
    yellow,
)
from omx.hud.constants import (
    HUD_RESIZE_RECONCILE_DELAY_SECONDS,
    HUD_TMUX_HEIGHT_LINES,
    HUD_TMUX_MAX_HEIGHT_LINES,
    HUD_TMUX_TEAM_HEIGHT_LINES,
)

__all__ = [
    "AutopilotStateForHud",
    "AutoresearchStateForHud",
    "DeepInterviewStateForHud",
    "DEFAULT_HUD_CONFIG",
    "HudConfig",
    "HudFlags",
    "HudGitConfig",
    "HudGitDisplay",
    "HudMetrics",
    "HudNotifyState",
    "HudPreset",
    "HudRenderContext",
    "RalphStateForHud",
    "RalplanStateForHud",
    "ResolvedHudConfig",
    "ResolvedHudGitConfig",
    "SessionStateForHud",
    "TeamStateForHud",
    "UltraqaStateForHud",
    "UltraworkStateForHud",
    "bold",
    "cyan",
    "dim",
    "get_ralph_color",
    "green",
    "is_color_enabled",
    "set_color_enabled",
    "yellow",
    "HUD_RESIZE_RECONCILE_DELAY_SECONDS",
    "HUD_TMUX_HEIGHT_LINES",
    "HUD_TMUX_MAX_HEIGHT_LINES",
    "HUD_TMUX_TEAM_HEIGHT_LINES",
]
