"""Team runtime: graceful shutdown entry point.

Port of ``shutdownTeam`` from ``src/team/runtime.ts`` (lines 2961-3310).
Phase 2.9b — sync-only, stdlib-only.

High-level flow (mirrors TS step-for-step, simplified for ported surface):

1. Sanitize ``team_name`` and read the config + manifest.
2. If no config, best-effort kill the tmux session and cleanup state.
3. **Send shutdown inboxes** to every worker via
   :func:`omx.team.state.shutdown.write_shutdown_request` plus a worker
   inbox file generated by
   :func:`omx.team.worker_bootstrap.generate_shutdown_inbox`.
4. **Wait for drain.** Poll up to ``drain_timeout_ms`` (default 15 000 ms,
   matching TS) for every worker to either ack the shutdown or have its
   pane go away. Sleep 2 s between rounds.
5. On any ``reject`` ack, raise ``shutdown_rejected`` unless ``force=True``.
6. **Force kill** remaining workers using
   :func:`omx.team.tmux_session.kill_worker`.
7. **Tear down** the tmux session (best-effort).
8. **Roll back** any worker worktrees via
   :func:`omx.team.worktree.rollback_provisioned_worktrees`.
9. **Cleanup** worktree-root AGENTS.md installs and the team worker
   instructions file.
10. **Write the final phase** as ``cancelled`` (or ``complete`` when no
    rejections happened), mark the leader session stopped, and call
    :func:`omx.team.team_ops.team_cleanup` to delete the team state dir
    (when ``confirm_issues=True`` or no failures were observed).

Simplifications relative to TS:

- **Mode-state sync** (``syncExactTeamModeStateOnShutdown``,
  ``matchesTeamModeStateForShutdown``) is stubbed. ``omx.modes.base.update_mode_state``
  is not yet ported (tracked separately). The stub is documented and
  intentionally never raises.
- **Shutdown gate / classification** (``classifyShutdown`` /
  ``shutdown_gate_blocked`` errors) is collapsed to the ``force`` flag
  and the per-worker ack check. The richer gate that inspects task
  counts will land alongside ``classifyShutdown`` in a later phase.
- **Commit hygiene** (``prepareWorkerWorktreeShutdownReports`` plus the
  ledger / artifact writers) is not run; the summary always returns
  ``commit_hygiene_artifacts=None``. Hygiene artifacts come from a TS
  pipeline that has not been ported yet.
- **Shared-session topology** (``resolveSharedSessionShutdownTopology``,
  ``teardownWorkerPanes`` async primitives) is folded into the simpler
  per-worker ``kill_worker`` loop, which is correct for the
  detached-session case the Python runtime exercises today.

The public API:

    shutdown_team(team_name: str, cwd: str,
                  options: ShutdownOptions | None = None,
                  *, drain_timeout_ms: int = 15_000) -> TeamShutdownSummary
"""

from __future__ import annotations

import time
from datetime import datetime, timezone
from typing import Any

from omx.team.contracts import TeamEvent
from omx.team.runtime_types import ShutdownOptions, TeamShutdownSummary
from omx.team.state.io import append_team_event
from omx.team.state.leader import mark_team_leader_session_stopped
from omx.team.state.monitor import write_phase_state
from omx.team.state.shutdown import read_shutdown_ack, write_shutdown_request
from omx.team.state.types import TeamPhaseState
from omx.team.state_root import team_dir as _team_dir
from omx.team.team_ops import (
    team_cleanup,
    team_read_config,
    team_read_manifest,
)
from omx.team.tmux_session import (
    destroy_team_session,
    is_worker_alive,
    kill_worker,
    sanitize_team_name,
)
from omx.team.worker_bootstrap import (
    generate_shutdown_inbox,
    remove_team_worker_instructions_file,
    remove_worker_worktree_root_agents_file,
)
from omx.team.worktree import (
    EnsureWorktreeResult,
    RollbackWorktreeOptions,
    rollback_provisioned_worktrees,
)

__all__ = ["shutdown_team"]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _config_is_empty(config: dict[str, Any] | None) -> bool:
    """Read_team_config returns ``{}`` when the file is missing."""
    return not config


def _worker_inbox_path(team_name: str, worker_name: str, cwd: str):
    return _team_dir(team_name, cwd) / "workers" / worker_name / "inbox.md"


def _write_worker_inbox_file(
    team_name: str, worker_name: str, content: str, cwd: str
) -> None:
    """Write the shutdown inbox markdown for a worker. Best-effort."""
    path = _worker_inbox_path(team_name, worker_name, cwd)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _sync_team_mode_state_on_shutdown(  # noqa: D401 - stub
    team_name: str,
    cwd: str,
    leader_session_id: str | None = None,
) -> None:
    """Best-effort mode-state sync stub.

    Port placeholder for TS ``syncTeamModeStateOnShutdown`` (runtime.ts:254-264).
    The TS implementation rewrites ``.omx/state/team-<sid>.json`` to flip
    ``active=false`` / ``current_phase=cancelled``. The Python
    ``omx.modes.base.update_mode_state`` helper is not yet ported, so this
    is intentionally a no-op. Hooked here so callers and tests can patch
    a single seam once the real implementation lands.

    Never raises — the TS version is best-effort.
    """
    return None


def _send_shutdown_inboxes(
    team_name: str,
    config: dict[str, Any],
    cwd: str,
) -> dict[str, str]:
    """Phase 1: write a shutdown request + inbox for every worker.

    Returns a map of ``worker_name -> requested_at`` so the drain loop can
    pass the minimum-timestamp gate to :func:`read_shutdown_ack`.

    Per-worker errors are swallowed (mirrors TS ``try/catch`` around the
    loop body): we want to make a best-effort attempt for every worker
    even if one of them already disappeared.
    """
    requested_at_by_worker: dict[str, str] = {}
    for worker in config.get("workers") or []:
        name = worker.get("name")
        if not name:
            continue
        try:
            requested_at = _now_iso()
            write_shutdown_request(team_name, name, cwd, requested_by="leader-fixed")
            requested_at_by_worker[name] = requested_at
            inbox = generate_shutdown_inbox(team_name, name)
            _write_worker_inbox_file(team_name, name, inbox, cwd)
        except Exception:  # noqa: BLE001 — TS swallows operation failures
            continue
    return requested_at_by_worker


def _worker_alive(
    session_name: str,
    worker: dict[str, Any],
) -> bool:
    """Return True iff the tmux pane for ``worker`` still has a live process."""
    pane_id = worker.get("pane_id")
    index = int(worker.get("index", 0))
    return is_worker_alive(
        session_name, index, pane_id if isinstance(pane_id, str) else None
    )


def _wait_for_drain(
    team_name: str,
    config: dict[str, Any],
    cwd: str,
    requested_at_by_worker: dict[str, str],
    force: bool,
    drain_timeout_ms: int,
    poll_interval_s: float = 2.0,
) -> list[tuple[str, str]]:
    """Phase 2: poll for ack or pane-gone until ``drain_timeout_ms`` elapses.

    Returns the list of ``(worker_name, reason)`` rejections collected. When
    a reject is observed and ``force=False``, raises ``shutdown_rejected``
    early so the caller can surface the failure without force-killing.
    """
    session_name = str(config.get("tmux_session") or "")
    workers = config.get("workers") or []
    if not workers:
        return []

    deadline_s = time.monotonic() + max(0.0, drain_timeout_ms / 1000.0)
    rejected: list[tuple[str, str]] = []
    acked: set[str] = set()

    while True:
        # Round of ack checks.
        for worker in workers:
            name = worker.get("name")
            if not name:
                continue
            ack = read_shutdown_ack(
                team_name, name, cwd, requested_at_by_worker.get(name)
            )
            if ack is None:
                continue
            if name not in acked:
                acked.add(name)
                try:
                    append_team_event(
                        cwd,
                        TeamEvent(
                            event_type="shutdown_ack",
                            timestamp=_now_iso(),
                            worker_id=name,
                            detail={
                                "reason": (
                                    f"reject:{ack.reason or 'no_reason'}"
                                    if ack.status == "reject"
                                    else "accept"
                                ),
                            },
                        ),
                        team_name,
                    )
                except Exception:  # noqa: BLE001
                    pass
            if ack.status == "reject":
                if not any(r[0] == name for r in rejected):
                    rejected.append((name, ack.reason or "no_reason"))

        if rejected and not force:
            detail = ",".join(f"{w}:{r}" for w, r in rejected)
            raise RuntimeError(f"shutdown_rejected:{detail}")

        any_alive = any(_worker_alive(session_name, w) for w in workers)
        if not any_alive:
            return rejected

        if time.monotonic() >= deadline_s:
            return rejected

        time.sleep(poll_interval_s)


def _teardown_worker_panes(config: dict[str, Any]) -> None:
    """Phase 3: force-kill any worker pane still alive.

    Mirrors the simplified detached-session branch of the TS shutdown.
    Leader and HUD panes are left alone — ``kill_worker`` guards against
    a worker pane id that happens to equal the leader pane.
    """
    session_name = str(config.get("tmux_session") or "")
    leader_pane_id = config.get("leader_pane_id")
    leader_pane = leader_pane_id if isinstance(leader_pane_id, str) else None
    for worker in config.get("workers") or []:
        pane_id = worker.get("pane_id")
        index = int(worker.get("index", 0))
        try:
            kill_worker(
                session_name,
                index,
                pane_id if isinstance(pane_id, str) else None,
                leader_pane,
            )
        except Exception:  # noqa: BLE001 — best-effort teardown
            continue


def _collect_provisioned_worktrees(
    config: dict[str, Any],
) -> list[EnsureWorktreeResult]:
    """Reconstruct ``EnsureWorktreeResult`` entries from the saved config.

    Only workers whose entry has ``worktree_path`` are included. The TS
    helper ``collectProvisionedShutdownWorktrees`` (runtime.ts) walks the
    same field; we materialize a minimal record because the rollback
    helper only consumes ``enabled``, ``created``, ``repo_root``,
    ``worktree_path``, ``branch_name`` and ``created_branch``.
    """
    results: list[EnsureWorktreeResult] = []
    leader_cwd = str(config.get("leader_cwd") or "")
    for worker in config.get("workers") or []:
        worktree_path = worker.get("worktree_path")
        if not isinstance(worktree_path, str) or not worktree_path:
            continue
        repo_root = str(worker.get("repo_root") or leader_cwd)
        if not repo_root:
            continue
        results.append(
            EnsureWorktreeResult(
                enabled=True,
                repo_root=repo_root,
                worktree_path=worktree_path,
                detached=bool(worker.get("worktree_detached", False)),
                branch_name=worker.get("worktree_branch"),
                created=bool(worker.get("worktree_created", True)),
                reused=bool(worker.get("worktree_reused", False)),
                created_branch=bool(worker.get("worktree_branch_created", False)),
            )
        )
    return results


def _cleanup_worktrees(
    config: dict[str, Any],
) -> list[str]:
    """Phase 4: roll back any worker worktrees provisioned at startup.

    Returns a list of cleanup error strings; never raises (callers append
    the errors and decide whether to raise at the end of shutdown).
    """
    errors: list[str] = []
    provisioned = _collect_provisioned_worktrees(config)
    if not provisioned:
        return errors
    try:
        rollback_provisioned_worktrees(
            provisioned,
            RollbackWorktreeOptions(skip_branch_deletion=False),
        )
    except Exception as err:  # noqa: BLE001
        errors.append(f"rollbackProvisionedWorktrees: {err}")
    return errors


def _remove_worktree_root_agents(team_name: str, config: dict[str, Any]) -> None:
    """Remove worker worktree-root AGENTS.md installs. Idempotent."""
    for worker in config.get("workers") or []:
        worktree_path = worker.get("worktree_path")
        team_state_root = worker.get("team_state_root")
        name = worker.get("name")
        if not (
            isinstance(worktree_path, str)
            and isinstance(team_state_root, str)
            and isinstance(name, str)
            and worktree_path
            and team_state_root
        ):
            continue
        try:
            remove_worker_worktree_root_agents_file(
                team_name, name, team_state_root, worktree_path
            )
        except Exception:  # noqa: BLE001 — best-effort
            continue


def _terminal_phase_for_shutdown(
    rejected: list[tuple[str, str]],
    force: bool,
    confirm_issues: bool,
) -> str:
    """Pick the terminal phase to record on shutdown.

    - Rejections (or a force shutdown) collapse to ``cancelled``.
    - Otherwise the terminal phase is ``complete``.

    ``confirm_issues`` does not change the terminal phase by itself — it
    only relaxes the cleanup gate.
    """
    if rejected or force:
        return "cancelled"
    return "complete"


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def shutdown_team(
    team_name: str,
    cwd: str,
    options: ShutdownOptions | None = None,
    *,
    drain_timeout_ms: int = 15_000,
    poll_interval_s: float = 2.0,
) -> TeamShutdownSummary:
    """Gracefully shut down a team and tear down its tmux + worktree state.

    Args:
        team_name: Caller-supplied team name. Sanitized before use.
        cwd: Working directory rooting the team's ``.omx/team`` state.
        options: Optional ``ShutdownOptions``. ``force=True`` skips the
            ack/reject gate and force-kills uncooperative workers.
            ``confirm_issues=True`` permits final state cleanup even when
            rejections were observed.
        drain_timeout_ms: Wait this long (ms) for workers to drain. The
            TS default is 15 000.
        poll_interval_s: Sleep this long between drain polls.

    Returns:
        :class:`TeamShutdownSummary`. ``commit_hygiene_artifacts`` is
        always ``None`` in this port — commit hygiene is run by a TS
        pipeline that has not been ported yet.

    Raises:
        RuntimeError: When ``force=False`` and at least one worker rejects
            the shutdown (``shutdown_rejected:<worker>:<reason>``), or when
            non-recoverable cleanup errors occurred after the panes were
            torn down.
    """
    opts = options or ShutdownOptions()
    force = opts.force
    confirm_issues = opts.confirm_issues

    sanitized = sanitize_team_name(team_name)
    # ``team_read_config`` is a direct re-export of ``state.io.read_team_config``
    # which takes ``(cwd, team_name)`` — it does not follow the (team_name, cwd)
    # convention documented on the team_ops gateway.
    config = team_read_config(cwd, sanitized)

    # Empty config: best-effort tmux session destroy + state cleanup.
    if _config_is_empty(config):
        try:
            destroy_team_session(f"omx-team-{sanitized}")
        except Exception:  # noqa: BLE001
            pass
        try:
            team_cleanup(cwd, sanitized)
        except Exception:  # noqa: BLE001
            pass
        _sync_team_mode_state_on_shutdown(sanitized, cwd)
        return TeamShutdownSummary(commit_hygiene_artifacts=None)

    manifest = team_read_manifest(sanitized, cwd)
    leader_session_id = ""
    if manifest is not None:
        raw_session_id = (
            getattr(getattr(manifest, "leader", None), "session_id", "") or ""
        )
        if isinstance(raw_session_id, str):
            leader_session_id = raw_session_id.strip()

    # Phase 1: send shutdown inboxes and request handshakes.
    requested_at_by_worker = _send_shutdown_inboxes(sanitized, config, cwd)

    # Phase 2: poll for drain. Raises ``shutdown_rejected`` when a worker
    # rejects and ``force`` is not set.
    rejected = _wait_for_drain(
        sanitized,
        config,
        cwd,
        requested_at_by_worker,
        force=force,
        drain_timeout_ms=drain_timeout_ms,
        poll_interval_s=poll_interval_s,
    )

    # Phase 3: force-kill remaining panes (always — even on graceful
    # shutdown, a Codex worker may have acked but not exited).
    _teardown_worker_panes(config)

    # Best-effort kill of the tmux session itself for non-shared sessions.
    session_name = str(config.get("tmux_session") or "")
    if session_name and ":" not in session_name:
        try:
            destroy_team_session(session_name)
        except Exception:  # noqa: BLE001
            pass

    # Phase 4: rollback worktrees + cleanup worker overlays / instructions.
    cleanup_errors: list[str] = []
    _remove_worktree_root_agents(sanitized, config)
    try:
        remove_team_worker_instructions_file(sanitized, cwd)
    except Exception:  # noqa: BLE001
        pass

    cleanup_errors.extend(_cleanup_worktrees(config))

    # Phase 5: write the final phase + mark leader stopped.
    terminal_phase = _terminal_phase_for_shutdown(rejected, force, confirm_issues)
    try:
        write_phase_state(
            _team_dir(sanitized, cwd),
            TeamPhaseState(current_phase=terminal_phase, updated_at=_now_iso()),
        )
    except Exception:  # noqa: BLE001
        pass
    try:
        mark_team_leader_session_stopped(sanitized, cwd, leader_session_id)
    except Exception:  # noqa: BLE001
        pass

    # Phase 6: cleanup team state directory.
    #
    # TS gates this on the classify-shutdown gate; in the simplified port
    # we cleanup unconditionally on success, and only when
    # ``confirm_issues=True`` if any rejection was observed. Force always
    # cleans up.
    can_cleanup = force or confirm_issues or not rejected
    team_state_cleaned = False
    if can_cleanup:
        try:
            team_cleanup(cwd, sanitized)
            team_state_cleaned = True
        except Exception as err:  # noqa: BLE001
            cleanup_errors.append(f"cleanupTeamState: {err}")
    if team_state_cleaned:
        _sync_team_mode_state_on_shutdown(sanitized, cwd, leader_session_id)

    if cleanup_errors:
        raise RuntimeError(" | ".join(cleanup_errors))

    return TeamShutdownSummary(commit_hygiene_artifacts=None)
